name: spack-build-cache
on:
  push:
    branches:
      - master

jobs:
  spack-build-cache:
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            compiler: "gcc",
            compiler-version: "10",
            os: "ubuntu-22.04",
            mpi: "mpich",
            mpi-version: ":",
          }
        - {
            compiler: "gcc",
            compiler-version: "11",
            os: "ubuntu-22.04",
            mpi: "mpich",
            mpi-version: ":",
          }
        - {
            compiler: "gcc",
            compiler-version: "12",
            os: "ubuntu-22.04",
            mpi: "mpich",
            mpi-version: ":",
          }
        - {
            compiler: "gcc",
            compiler-version: "12",
            os: "ubuntu-24.04",
            mpi: "mpich",
            mpi-version: ":",
          }
        - {
            compiler: "gcc",
            compiler-version: "13",
            os: "ubuntu-24.04",
            mpi: "mpich",
            mpi-version: ":",
          }
        - {
            compiler: "gcc",
            compiler-version: "14",
            os: "ubuntu-24.04",
            mpi: "mpich",
            mpi-version: ":",
          }
        - {
            compiler: "gcc",
            compiler-version: "10",
            os: "ubuntu-22.04",
            mpi: "openmpi",
            mpi-version: ":",
          }
        - {
            compiler: "gcc",
            compiler-version: "11",
            os: "ubuntu-22.04",
            mpi: "openmpi",
            mpi-version: ":",
          }
        - {
            compiler: "gcc",
            compiler-version: "12",
            os: "ubuntu-22.04",
            mpi: "openmpi",
            mpi-version: ":",
          }
        - {
            compiler: "gcc",
            compiler-version: "12",
            os: "ubuntu-24.04",
            mpi: "openmpi",
            mpi-version: ":",
          }
        - {
            compiler: "gcc",
            compiler-version: "13",
            os: "ubuntu-24.04",
            mpi: "openmpi",
            mpi-version: ":",
          }
        - {
            compiler: "gcc",
            compiler-version: "14",
            os: "ubuntu-24.04",
            mpi: "openmpi",
            mpi-version: ":",
          }
        - {
            compiler: "intel",
            compiler-version: "2023.2.1",
            os: "ubuntu-22.04",
            mpi: "intel-oneapi-mpi",
            mpi-version: "2021.14",
          }
        - {
            compiler: "intel",
            compiler-version: "2023.2.1",
            os: "ubuntu-24.04",
            mpi: "intel-oneapi-mpi",
            mpi-version: "2021.14",
          }
        - {
            compiler: "oneapi",
            compiler-version: "2025.0",
            os: "ubuntu-22.04",
            mpi: "intel-oneapi-mpi",
            mpi-version: "2021.14",
          }
        - {
            compiler: "oneapi",
            compiler-version: "2025.0",
            os: "ubuntu-24.04",
            mpi: "intel-oneapi-mpi",
            mpi-version: "2021.14",
          }
    runs-on: ${{ matrix.config.os }}
    permissions:
      packages: write
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
      - name: "Get Spack"
        uses: spack/setup-spack@v2.1.1
      - name: "Get Intel"
        uses: NOAA-EMC/ci-install-intel-toolkit@develop
        if: ${{ matrix.config.compiler == 'intel' || matrix.config.compiler == 'oneapi' }}
        with:
          install-classic: ${{ matrix.config.compiler == 'intel' }}
          classic-version: ${{ matrix.config.compiler-version }}
          install-oneapi: ${{ matrix.config.compiler == 'oneapi' }}
          oneapi-version: ${{ matrix.config.compiler-version }}
          install-mpi: true
          mpi-version: ${{ matrix.config.mpi-version }}
          compiler-setup: ${{ matrix.config.compiler }}
      - name: "Build and cache packages"
        shell: spack-bash {0}
        env:
          OCI_USERNAME: ${{ github.repository_owner }}
          OCI_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          sudo mv /usr/local /usr/local_mv
          # Set up mirror for build caching:
          spack mirror add spack-build-cache oci://ghcr.io/$OCI_USERNAME/ci-playground
          spack mirror set --push --oci-username-variable OCI_USERNAME --oci-password-variable OCI_TOKEN spack-build-cache
          COMPILER="${{ matrix.config.compiler }}@${{ matrix.config.compiler-version }}"
          # Activate environment and set up compilers:
          spack env activate .
          if [ ${{ matrix.config.compiler }} == 'gcc' ]; then
            sudo apt install gcc-${{ matrix.config.compiler-version }} g++-${{ matrix.config.compiler-version }} gfortran-${{ matrix.config.compiler-version }}
            spack config add "packages:gcc-runtime:require:'%gcc@${{ matrix.config.compiler-version }}'"
          else # set GCC backend for Intel to be the Ubuntu default version of GCC
            if [ ${{ matrix.config.os }} == ubuntu-22.04 ]; then gccver=11; fi
            if [ ${{ matrix.config.os }} == ubuntu-24.04 ]; then gccver=13; fi
            spack config add "packages:gcc-runtime:require:'%gcc@${gccver}'"
          fi
          if [ ${{ matrix.config.compiler }} == 'oneapi' ]; then
            spack compiler find /opt/intel/oneapi/compiler/${{ matrix.config.compiler-version }}/linux
          elif [ ${{ matrix.config.compiler }} == 'intel' ]; then
            intelversion=$(spack compiler find /opt/intel/oneapi/compiler/${{ matrix.config.compiler-version }}/linux/bin/intel64/ | grep -oP "intel@\K[\d\.]+")
            sed 's|environment: {}|environment:\n        prepend_path: {LD_LIBRARY_PATH: /opt/intel/oneapi/compiler/${{ matrix.config.compiler-version }}/linux/compiler/lib/intel64_lin}|' -i spack.yaml
            COMPILER=intel@$intelversion
          fi
          spack config add "packages:all:prefer:['%$COMPILER']"
          # MPI setup. Always use external to avoid a mess of dependencies.
          # This means that users of any cached MPI-based packages must have
          # the appropriate MPI library installed in their own workflow via apt.
          spack config add "packages:mpi:require:'${{ matrix.config.mpi }}@${{ matrix.config.mpi-version }}'"
          if [ "${{ matrix.config.mpi }}" == intel-oneapi-mpi ]; then
            sed -i "s|^  packages:|  packages:\n    intel-oneapi-mpi:\n      buildable: false\n      externals:\n      - spec: intel-oneapi-mpi@${{ matrix.config.mpi-version }}\n        prefix: /opt/intel/oneapi|" spack.yaml
            spack config add "packages:mpi:buildable:false"
          fi
          # Find externals, including MPI:
          spack external find --all --exclude intel --exclude oneapi --exclude clang --exclude llvm --exclude llvm-doe --exclude curl --exclude zlib
          cat spack.yaml
          # Build-n-cache:
          spack concretize --fresh |& tee log.concretize
          set +e
          spack install --no-check-signature --show-log-on-error --fail-fast
          rc=$?
          set -e
          spack buildcache push --update-index spack-build-cache
          return $rc
