name: Test

on: [workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - uses: spack/setup-spack@v2

      - name: Run tests
        shell: spack-bash {0}
        run: |
          echo SPACK_ROOT: $SPACK_ROOT
