name: containers
on:
  push:
    branches:
      - master

jobs:
  container-build:
    strategy:
      matrix:
        os: [ubuntu-24.04]
    runs-on: ${{ matrix.os }}
    permissions:
      packages: write

    steps:

      - name: "Get Spack"
        uses: spack/setup-spack@v2.1.1

      - name: "Spack build"
        shell: spack-bash {0}
        env:
          OCI_USERNAME: ${{ github.repository_owner }}
          OCI_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OSLABEL: ${{ matrix.os }}
        run: |
          spack env create test
          spack env activate test
          spack mirror add --unsigned spack-build-cache oci://ghcr.io/$OCI_USERNAME/ci-playground
          spack mirror set --push --oci-username-variable OCI_USERNAME --oci-password-variable OCI_TOKEN spack-build-cache
          spack add gmake
          spack concretize
          spack install --no-check-signature
          spack buildcache push --unsigned spack-build-cache gmake
          spack buildcache update-index spack-build-cache
          echo -e "  container:\n    images:\n      os: '${OSLABEL/-/:}'\n      spack: develop" >> $SPACK_ENV/spack.yaml
          cd $SPACK_ENV
          spack containerize > Dockerfile
          sudo docker build -t myapp-${OSLABEL} .
