name: test123
on:
  push:
    branches:
      - master

jobs:
  test123:
    runs-on: ubuntu-latest
    steps:
      - name: "run shell"
        shell: bash
        run: |
          echo A > file1
          echo B > file2
          echo C > file3
          tar -cf myarchive.tar file1 file2 file3
          skopeo login --username ${{ github.repository_owner }} --password ${{ secrets.MYSECONDTESTSECRET }}
          skopeo copy --all oci-archive:myarchive.tar docker://ghcr.io/${{ github.repository }}
