name: spack-build-cache
on:
  push:
    branches:
      - master

jobs:
  spack-build-cache:
    strategy:
      matrix:
        config:
        - {
            name: "gcc",
            version: "10",
            os: "ubuntu-22.04",
          }
        - {
            name: "gcc",
            version: "11",
            os: "ubuntu-22.04",
          }
        - {
            name: "gcc",
            version: "12",
            os: "ubuntu-22.04",
          }
        - {
            name: "gcc",
            version: "12",
            os: "ubuntu-24.04",
          }
        - {
            name: "gcc",
            version: "13",
            os: "ubuntu-24.04",
          }
        - {
            name: "gcc",
            version: "14",
            os: "ubuntu-24.04",
          }
        - {
            name: "intel",
            version: "2023.2.1",
            os: "ubuntu-22.04",
          }
        - {
            name: "intel",
            version: "2023.2.1",
            os: "ubuntu-24.04",
          }
        - {
            name: "oneapi",
            version: "2023.2.1",
            os: "ubuntu-22.04",
          }
        - {
            name: "oneapi",
            version: "2023.2.1",
            os: "ubuntu-24.04",
          }
        - {
            name: "oneapi",
            version: "2025.0",
            os: "ubuntu-22.04",
          }
        - {
            name: "oneapi",
            version: "2025.0",
            os: "ubuntu-24.04",
          }
    runs-on: ${{ matrix.config.os }}
    permissions:
      packages: write
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
      - name: "Get Spack"
        uses: spack/setup-spack@v2.1.1
      - name: "Get Intel"
        uses: NOAA-EMC/ci-install-intel-toolkit@develop
        if: ${{ matrix.config.name == 'intel' || matrix.config.name == 'oneapi' }}
        with:
          install-classic: ${{ matrix.config.name == 'intel' }}
          classic-version: ${{ matrix.config.version }}
          install-oneapi: ${{ matrix.config.name == 'oneapi' }}
          oneapi-version: ${{ matrix.config.version }}
          install-mpi: true
          compiler-setup: ${{ matrix.config.name }}
      - name: "Build and cache packages"
        shell: spack-bash {0}
        env:
          OCI_USERNAME: ${{ github.repository_owner }}
          OCI_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          spack mirror add spack-build-cache oci://ghcr.io/$OCI_USERNAME/ci-playground
          spack mirror set --push --oci-username-variable OCI_USERNAME --oci-password-variable OCI_TOKEN spack-build-cache
          COMPILER="${{ matrix.config.name }}@${{ matrix.config.version }}"
          sed "s|@COMPILER@|$COMPILER|" spack.yaml.in > spack.yaml
          if [ ${{ matrix.config.name }} == 'gcc' ]; then
            sudo apt install gcc-${{ matrix.config.version }} g++-${{ matrix.config.version }} gfortran-${{ matrix.config.version }}
          elif [[ " intel oneapi " =~ " ${{ matrix.config.name }} " ]]; then
            spack compiler find /opt/intel/oneapi/compiler/${{ matrix.config.version }}/linux
          fi
          cat spack.yaml
          spack -e . concretize --fresh |& tee log.concretize
          spack -e . install --no-check-signature --fail-fast --show-log-on-error
          spack -e . buildcache push --update-index spack-build-cache
