name: test123
on:
  push:
    branches:
      - master

jobs:
  test123:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: "run shell"
        shell: bash
        env:
          OCI_USERNAME: AlexanderRichert-NOAA
          OCI_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git clone --depth 1 https://github.com/spack/spack
          cd spack
          . share/spack/setup-env.sh
          spack mirror add spack-build-cache oci://ghcr.io/$OCI_USERNAMEspack mirror set --oci-username-variable/ci-playground
          spack mirror set --oci-username $OCI_USERNAME --oci-password $OCI_TOKEN spack-build-cache
          spack install gmake
          spack buildcache push spack-build-cache gmake
