name: test123
on:
  push:
    branches:
      - master

jobs:
  test123:
    runs-on: ubuntu-latest
    steps:
#      - name: "run shell"
#        shell: bash
#        env:
#          mysecret: ${{ secrets.MYTESTSECRET }}
#        run: |
#          echo A > file1
#          echo B > file2
#          echo C > file3
#          tar -cf myarchive.tar file1 file2 file3
#          skopeo login --username ${{ github.repository_owner }} --password $mysecret ghcr.io
#          skopeo copy --all oci-archive:myarchive.tar docker://ghcr.io/$(echo ${{ github.repository }} | tr [A-Z] [a-z])
      - name: "build w3emc"
        uses: AlexanderRichert-NOAA/build-nceplibs@develop
        with:
          bacio-version: v2.6.0
          w3emc-version: v2.10.0
          bufr-version: v12.0.1
          repo-cache: true
