name: test123
on:
  push:
    branches:
      - master

jobs:
  test123:
    runs-on: ubuntu-latest
    steps:
#      - name: "run shell"
#        shell: bash
#        env:
#          mysecret: ${{ secrets.MYTESTSECRET }}
#        run: |
#          echo A > file1
#          echo B > file2
#          echo C > file3
#          tar -cf myarchive.tar file1 file2 file3
#          skopeo login --username ${{ github.repository_owner }} --password $mysecret ghcr.io
#          skopeo copy --all oci-archive:myarchive.tar docker://ghcr.io/$(echo ${{ github.repository }} | tr [A-Z] [a-z])
#      - name: "build various"
#        uses: AlexanderRichert-NOAA/build-nceplibs@develop
#        with:
#          bacio-version: v2.6.0
#          w3emc-version: v2.10.0
#          jasper-version: version-2.0.25
#          g2-version: v3.4.5
#          g2c-version: v1.8.0
#          ip-version: v4.4.0
#          sp-version: v2.5.0
#          bufr-version: v12.0.1
#          repo-cache: true
#      - name: 'install intel'
#        uses: AlexanderRichert-NOAA/install-intel@develop
      - name: 'test'
        run: |
          echo 1
          which git
          echo 2
          git --version
          echo 3
          ls /usr/bin | grep git
