name: spack-build-cache
on:
  push:
    branches:
      - master

jobs:
  spack-build-cache:
    strategy:
      matrix:
        compiler:
        - {
            name: "gcc"
            version: "10"
          }
        - {
            name: "gcc"
            version: "11"
          }
        - {
            name: "gcc"
            version: "12"
          }
        - {
            name: "gcc"
            version: "13"
          }
        - {
            name: "gcc"
            version: "14"
          }
        - {
            name: "intel",
          }
        - {
            name: "oneapi",
            version: "2023.2.1"
          }
        - {
            name: "oneapi",
            version: "2025.0"
          }
        os: [ubuntu-22.04, ubuntu-24.04]
        exclude:
          - compiler.name: gcc
            compiler.version: 13
            os: ubuntu-22.04
          - compiler.name: gcc
            compiler.version: 14
            os: ubuntu-22.04
          - compiler.name: gcc
            compiler.version: 10
            os: ubuntu-24.04
          - compiler.name: gcc
            compiler.version: 11
            os: ubuntu-24.04
    runs-on: ${{ matrix.os }}
    permissions:
      packages: write
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
      - name: "Get Spack"
        uses: spack/setup-spack@v2.1.1
      - name: "Get Intel"
        uses: NOAA-EMC/ci-install-intel-toolkit@develop
        if: ${{ matrix.compiler.name == 'intel' || matrix.compiler.name == 'oneapi' }}
        with:
          install-classic: ${{ matrix.compiler.name == 'intel' }}
          install-oneapi: ${{ matrix.compiler.name == 'oneapi' }}
          oneapi-version: ${{ matrix.compiler.version }}
          install-mpi: true
          compiler-setup: ${{ matrix.compiler.name }}
      - name: "Build and cache packages"
        shell: spack-bash {0}
        env:
          OCI_USERNAME: ${{ github.repository_owner }}
          OCI_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          spack mirror add spack-build-cache oci://ghcr.io/$OCI_USERNAME/ci-playground
          spack mirror set --push --oci-username-variable OCI_USERNAME --oci-password-variable OCI_TOKEN spack-build-cache
          if [ ${{ matrix.compiler.name }} == 'gcc' ]; then
            sudo apt install gcc-${{ matrix.compiler.version }} g++-${{ matrix.compiler.version }} gfortran-${{ matrix.compiler.version }}
          fi
          COMPILER=${{ matrix.compiler.name }}@${{ matrix.compiler.version }}
          sed "s|@COMPILER@|$COMPILER|" spack.yaml.in > spack.yaml
          cat spack.yaml
          spack compiler find
          spack -e . concretize |& tee log.concretize
          spack -e . install --no-check-signature --fail-fast --show-log-on-error
          spack -e . buildcache push --update-index spack-build-cache
