name: containers
#on: false
on:
  push:
    branches:
      - master

jobs:
  container-run-test:
    runs-on: ubuntu-24.04
    container:
      image: ghcr.io/alexanderrichert-noaa/ci-playground-ubuntu-24.04:master
    steps:
      - name: test
        env:
          PATH: /opt/views/view/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
        run: |
          git clone --recurse-submodules https://github.com/ufs-community/ufs-weather-model
          cd ufs-weather-model
          mkdir build
          cd build
          cmake .. -DAPP=ATM
          make -j2
